<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>ProductionLineManage.Services</RootNamespace>
    <AssemblyName>ProductionLineManage.Services</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NPOI" Version="2.7.3" />
    <PackageReference Include="OpcUaHelper" Version="2.2.1" />
    <PackageReference Include="Prism.Unity" Version="8.1.97" />
    <PackageReference Include="S7netplus" Version="0.20.0" />
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
    <PackageReference Include="System.Threading.Channels" Version="8.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\02_Infrastructure\ProductionLineManage.Infrastructure\ProductionLineManage.Infrastructure.csproj" />
    <ProjectReference Include="..\..\02_Infrastructure\ProductionLineManage.Shared\ProductionLineManage.Shared.csproj" />
    <ProjectReference Include="..\..\03_Core\ProductionLineManage.Core\ProductionLineManage.Core.csproj" />
  </ItemGroup>
</Project>
